server:
  port: ${SERVER_PORT}
  tomcat:
    relaxed-query-chars: "|,{,},[,]"

spring:
  application:
    api-prefix: /api/v1
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  signal-key: ${JWT_SECRET}
  google:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
  upload:
    avatar-dir: ${UPLOAD_DIR}
  public:
    avatar-base-url: /img/avatar

PayOS:
  clientId: ${PAYOS_CLIENT_ID}
  clientSecret: ${PAYOS_API_KEY}
  checksumKey: ${PAYOS_CHECKSUM_KEY}
